apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: syfo-mikrofrontend
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  envFrom:
    - secret: syfo-mikrofrontend-secrets
  image: {{ image }}
  port: 8080
  tokenx:
    enabled: true
  idporten:
    enabled: true
    sidecar:
      enabled: true
  liveness:
    path: /syfo-mikrofrontend/internal/isAlive
    initialDelay: 10
  readiness:
    path: /syfo-mikrofrontend/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /syfo-mikrofrontend/internal/metrics
  replicas:
    min: 2
    max: 4
  ingresses:
    - "https://www.nav.no/syfo-mikrofrontend"
  env:
    - name: ISDIALOGMOTE_HOST
      value: "https://isdialogmote.nav.no"
    - name: ISDIALOGMOTE_CLIENT_ID
      value: "prod-gcp:teamsykefravr:isdialogmote"
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "500m"
      memory: 512Mi
