apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: aktivitetskrav-mikrofrontend
  namespace: team-esyfo
  labels:
    team: team-esyfo
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /aktivitetskrav-mikrofrontend/internal/isAlive
    initialDelay: 10
  readiness:
    path: /aktivitetskrav-mikrofrontend/internal/isReady
    initialDelay: 10
  prometheus:
    enabled: true
    path: /aktivitetskrav-mikrofrontend/internal/metrics
  replicas:
    min: 2
    max: 4
  ingresses:
    - "https://www.intern.dev.nav.no/aktivitetskrav-mikrofrontend"
  resources:
    limits:
      cpu: "3"
      memory: 768Mi
    requests:
      cpu: "500m"
      memory: 512Mi
